ARG ELK_VERSION
ARG OSS_STRING="-oss"

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana${OSS_STRING}:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
