ARG ELK_VERSION
ARG OSS_STRING="-oss"

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch${OSS_STRING}:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
