ARG ELK_VERSION
ARG OSS_STRING="-oss"

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash${OSS_STRING}:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
